# Generated by Django 2.1 on 2019-12-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djnago_press', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
