# Generated by Django 2.1 on 2019-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_page', '0002_auto_20191204_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='in_nav',
            field=models.BooleanField(default=False),
        ),
    ]
