# Generated by Django 2.1 on 2019-12-07 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_press', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/css', validators=[django.core.validators.FileExtensionValidator(['css'])])),
            ],
        ),
        migrations.CreateModel(
            name='FontsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/fonts')),
            ],
        ),
        migrations.CreateModel(
            name='JSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/js', validators=[django.core.validators.FileExtensionValidator(['js'])])),
            ],
        ),
        migrations.CreateModel(
            name='StaticFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('css_files', models.ManyToManyField(blank=True, to='django_press.CSSFile')),
                ('fonts_file', models.ManyToManyField(blank=True, to='django_press.FontsFile')),
                ('js_files', models.ManyToManyField(blank=True, to='django_press.JSFile')),
            ],
        ),
    ]
