# Generated by Django 2.1 on 2019-12-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_press', '0002_cssfile_fontsfile_jsfile_staticfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticfiles',
            name='css_files',
        ),
        migrations.RemoveField(
            model_name='staticfiles',
            name='fonts_file',
        ),
        migrations.RemoveField(
            model_name='staticfiles',
            name='js_files',
        ),
        migrations.DeleteModel(
            name='CSSFile',
        ),
        migrations.DeleteModel(
            name='FontsFile',
        ),
        migrations.DeleteModel(
            name='JSFile',
        ),
        migrations.DeleteModel(
            name='StaticFiles',
        ),
    ]
