# Generated by Django 2.1 on 2019-12-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_press', '0005_remove_imageslider_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='icofont icofont-light-bulb', help_text='https://icofont.com/icons 参照', max_length=100, verbose_name='icon class')),
                ('name', models.CharField(max_length=30, verbose_name='サービス名')),
                ('description', models.TextField(verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_press.PageContent')),
                ('title', models.CharField(max_length=30, verbose_name='見出し')),
                ('abstract', models.TextField(help_text='Markdown、HTMLでの記述が可能です。2,3行ぐらいが好ましいです。', verbose_name='概要')),
                ('products', models.ManyToManyField(to='django_press.Product', verbose_name='サービス')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_press.pagecontent',),
        ),
    ]
