# Generated by Django 2.1 on 2019-12-08 22:30

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_press', '0006_product_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_press.PageContent')),
            ],
            options={
                'verbose_name': 'タブを使う',
            },
            bases=('django_press.pagecontent',),
        ),
        migrations.CreateModel(
            name='TabElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タブの見出し')),
                ('content', markdownx.models.MarkdownxField(help_text='Markdown、HTMLでの記述が可能です。ドラッグアンドドロップで画像の配置もできます。', verbose_name='タブの中身')),
            ],
        ),
        migrations.AlterModelOptions(
            name='imageslider',
            options={'verbose_name': '画像のスライドショー'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Webページ', 'verbose_name_plural': 'Webページ'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ('priority',), 'verbose_name': 'ページの構成要素', 'verbose_name_plural': 'ページの構成要素'},
        ),
        migrations.AlterModelOptions(
            name='pagetext',
            options={'verbose_name': '文章と画像に最適'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'サービスなどを伝える'},
        ),
        migrations.AddField(
            model_name='tab',
            name='tabs',
            field=models.ManyToManyField(to='django_press.TabElement', verbose_name='タブ要素'),
        ),
    ]
