# Generated by Django 2.1 on 2019-12-09 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_press', '0008_page_parent_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='imagefile',
            options={'verbose_name': '写真', 'verbose_name_plural': '写真'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '紹介する系', 'verbose_name_plural': '紹介する系'},
        ),
        migrations.AlterModelOptions(
            name='tabelement',
            options={'verbose_name': 'タブ要素', 'verbose_name_plural': 'タブ要素'},
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('formfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_press.FormField')),
                ('require', models.BooleanField(default=True, verbose_name='必須項目ならTrueにしてください')),
            ],
            options={
                'verbose_name': 'テキスト',
            },
            bases=('django_press.formfield',),
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_press.Form'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_django_press.formfield_set+', to='contenttypes.ContentType'),
        ),
    ]
