# Generated by Django 2.1 on 2019-12-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_press', '0009_auto_20191209_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='フォーム名'),
        ),
    ]
