# Generated by Django 2.1 on 2019-12-09 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_press', '0010_form_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('pagecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_press.PageContent')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_press.Form', verbose_name='フォーム')),
            ],
            options={
                'verbose_name': 'フォームを使う',
            },
            bases=('django_press.pagecontent',),
        ),
    ]
