# Generated by Django 2.1 on 2019-12-09 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_press', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanField',
            fields=[
                ('formfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_press.FormField')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('django_press.formfield',),
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='require',
        ),
        migrations.AddField(
            model_name='formfield',
            name='help_text',
            field=models.CharField(default='', max_length=200, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='initial',
            field=models.CharField(default='', max_length=100, verbose_name='初期値'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='label',
            field=models.CharField(default='', max_length=100, verbose_name='ラベル'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='label_suffix',
            field=models.CharField(default='', max_length=30, verbose_name='ラベルの接尾辞'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='required',
            field=models.BooleanField(default=True, verbose_name='必須項目でなければチェックを外してください'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='empty_value',
            field=models.CharField(default='', max_length=30, verbose_name='空を表す文字'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='max_length',
            field=models.PositiveSmallIntegerField(default=300, verbose_name='最大文字数'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='min_length',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='最小文字数'),
        ),
        migrations.AddField(
            model_name='textfield',
            name='strip',
            field=models.BooleanField(default=True, verbose_name='前後の空白を除く'),
        ),
    ]
